# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build demo-devops`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t demo-devops`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system demo-devops && \
          adduser --system -G demo-devops demo-devops

COPY dist/demo-devops demo-devops
RUN chown -R demo-devops:demo-devops .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix demo-devops --omit=dev -f install

CMD [ "node", "demo-devops" ]
